import React from "react"
import "./Home.scss"
import Featured from "../../components/featured/Featured"

const Home = () => {
    return (
        <div className="Home">
            <Featured/>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, fugit dolore similique non pariatur, molestiae quae sapiente soluta animi deleniti quia, est dicta? Tenetur sit quaerat molestias ad tempora consequatur amet voluptatum et dignissimos alias, non corrupti error perferendis eveniet sint. Distinctio, commodi! Est porro neque qui, rem voluptates expedita quae, voluptate cupiditate consectetur dolor nam quidem ab suscipit ea! Facere, nisi voluptates at, labore sunt error laborum dolor quia accusamus, sit temporibus recusandae animi quas. Pariatur, veritatis error quod ut deleniti nihil nulla sapiente in sequi id, officiis ipsa! Fugit asperiores sed excepturi quis ex iusto quae veritatis voluptatum!</p>
        </div>
    )
}

export default Home